Proceso sin_titulo
	Definir N1, N2, N3, S, R, M COMO ENTERO;
	ESCRIBIR "INGRESAR PRIMER NÚMERO ";
	LEER N1;
	ESCRIBIR "INGRESAR SEGUNDO NÚMERO ";
	LEER N2;
	ESCRIBIR "INGRESAR TERCER NÚMERO" ;
	LEER N3;
	S<- N1+N2+N3;
	R<- N1-N2-N3;
	M<- N1*N2*N3;
	ESCRIBIR "LA SUMA ES ", S;
	ESCRIBIR "LA RESTA ES ", R;
	ESCRIBIR "LA MULTIPLICACIÓN ES ", M;
	
FinProceso
